joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 500

pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - robot_shoulder_pan_joint
    - robot_shoulder_lift_joint
    - robot_elbow_joint
    - robot_wrist_1_joint
    - robot_wrist_2_joint
    - robot_wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    robot_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    robot_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    robot_elbow_joint: {trajectory: 0.1, goal: 0.1}
    robot_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    robot_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    robot_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

joint_group_pos_controller:
  type: position_controllers/JointGroupPositionController
  joints: 
    - robot_shoulder_pan_joint
    - robot_shoulder_lift_joint
    - robot_elbow_joint
    - robot_wrist_1_joint
    - robot_wrist_2_joint
    - robot_wrist_3_joint
