# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: main
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - robot_shoulder_pan_joint
    - robot_shoulder_lift_joint
    - robot_elbow_joint
    - robot_wrist_1_joint
    - robot_wrist_2_joint
    - robot_wrist_3_joint
    - gripper_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
gripper_controller:
  type: position_controllers/JointPositionController
  joints:
    gripper_finger_joint
  gains:
    gripper_finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_controller:
  type: position_controllers/JointPositionController
  joints:
    - robot_shoulder_pan_joint
    - robot_shoulder_lift_joint
    - robot_elbow_joint
    - robot_wrist_1_joint
    - robot_wrist_2_joint
    - robot_wrist_3_joint
  gains:
    robot_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1